const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAILED: "FETCH_POSITION_FAILED",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILED: "FETCH_ROLE_FAILED",

  CREATE_USE_SUCCESS: "CREATE_USE_SUCCESS",
  CREATE_USE_FAILED: "CREATE_USE_FAILED",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAILED: "FETCH_ALL_USER_FAILED",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",

  FETCH_TOP_DOCTOR_SUCCESS: "FETCH_TOP_DOCTOR_SUCCESS",
  FETCH_TOP_DOCTOR_FAILED: "FETCH_TOP_DOCTOR_FAILED",

  FETCH_ALL_DOCTORS_SUCCESS: "FETCH_ALL_DOCTORS_SUCCESS",
  FETCH_ALL_DOCTORS_FAILED: "FETCH_ALL_DOCTORS_FAILED",

  SAVE_INFO_DOCTORS_SUCCESS: "SAVE_INFODOCTORS_SUCCESS",
  SAVE_INFO_DOCTORS_FAILED: "SAVE_INFODOCTORS_FAILED",

  FETCH_INFO_DOCTORS_SUCCESS: "FETCH_INFO_DOCTORS_SUCCESS",
  FETCH_INFO_DOCTORS_FAILED: "FETCH_INFO_DOCTORS_FAILED",

  SAVE_ID_DOCTOR: "SAVE_ID_DOCTOR",

  FETCH_ALL_TIME_SUCCESS: "FETCH_ALL_TIME_SUCCESS",
  FETCH_ALL_TIME_FAILED: "FETCH_ALL_TIME_FAILED",

  FETCH_REQUIRED_DOCTOR_START: "FETCH_REQUIRED_DOCTOR_START",
  FETCH_REQUIRED_DOCTOR_SUCCESS: "FETCH_REQUIRED_DOCTOR_SUCCESS",
  FETCH_REQUIRED_DOCTOR_FAILED: "FETCH_REQUIRED_DOCTOR_FAILED",
});

export default actionTypes;
